import * as React from 'react';
import WindPowerOutlinedIcon from '@mui/icons-material/WindPowerOutlined';
interface Category {
    label: string, 
    icon?: string
}
export const categoryList: Category[] = [
    {label: '최고의 전망', icon: ''},
    {label: '한적한 시골', icon: ''},
    {label: '국립공원', icon: ''},
    {label: '풍차', icon: '<WindPowerOutlinedIcon />'},
    {label: '컨테이너하우스', icon: ''},
    {label: '셰어하우스', icon: ''},
    {label: '해변 바로 앞', icon: ''},
    {label: '료칸', icon: ''},
    {label: '기상천외한 숙소', icon: ''},
    {label: '캠핑카', icon: ''},
    {label: '멋진 수영장', icon: ''},
    {label: '농장', icon: ''},
    {label: '초소형 주택', icon: ''},
    {label: '통나무집', icon: ''},
    {label: '디자인', icon: ''},
    {label: '캐슬', icon: ''},
    {label: '저택', icon: ''},
    {label: '열대 지역', icon: ''},
    {label: '상징적 도시', icon: ''},
    {label: '북극', icon: ''},
    {label: '스키', icon: ''},
    {label: '호수 근처', icon: ''},
    {label: 'Luxe', icon: ''},
    {label: 'B&B', icon: ''},
    {label: '유서 깊은 주택', icon: ''},
    {label: '호숫가', icon: ''},
    {label: '와인 농장', icon: ''},
    {label: '속세를 벗어난 숙소', icon: ''},
    {label: '사막', icon: ''},
    {label: '창작 공간', icon: ''},
    {label: '섬', icon: ''},
    {label: '스키를 탄 채로 출입 가능', icon: ''},
    {label: '동굴', icon: ''},
    {label: '트리하우스', icon: ''},
    {label: 'A자형 주택', icon: ''},
    {label: '복토 주택', icon: ''},
    {label: '그랜드 피아노', icon: ''},
    {label: '보트', icon: ''},
    {label: '전문가급 주방', icon: ''},
    {label: '골프장', icon: ''},
    {label: '서핑', icon: ''},
    {label: '돔하우스', icon: ''},
    {label: '리아드', icon: ''},
    {label: '타워', icon: ''},
    {label: '하우스보트', icon: ''},
    {label: '헛간', icon: ''},
    {label: '민수', icon: ''},
    {label: '키클라데스 주택', icon: ''},
    {label: '카사 파르티쿨라르', icon: ''},
    {label: '마차', icon: ''},
    {label: '유르트', icon: ''},
    {label: '트룰로', icon: ''},
    {label: '캠핑장', icon: ''},
    {label: '담무소', icon: ''},
    {label: '해변 근처', icon: ''}
]